version: "3.8"

services:
  web:
    image: njunu/authenticate-api:prod
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432

  db-migrator:
    image: njunu/authenticate-api:prod
    command:
      [
        "./wait-for",
        "--timeout=300",
        "database:5432",
        "--",
        "bin/rails",
        "db:migrate",
      ]
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    deploy:
      restart_policy:
        condition: none
